# Generated by Django 5.2.5 on 2025-08-25 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_users_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notes',
            new_name='note',
        ),
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
