# Generated by Django 5.2.5 on 2025-08-26 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_notes_note_rename_users_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='untitled', max_length=100),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
            preserve_default=False,
        ),
    ]
